---
name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-22.04
    steps:
      # checks out the repo
      - uses: actions/checkout@v4
      # setup python
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # run pre-commit
      - uses: pre-commit/action@v3.0.1
